name: Build AbbBackup Console App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Publish
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # adapte si tu utilises une autre version

    - name: Restore dependencies
      run: dotnet restore AbbBackup.csproj

    - name: Build project
      run: dotnet build AbbBackup.csproj --configuration Release --no-restore
    - name: Publish project
      run: dotnet publish AbbBackup.csproj --configuration Release --output ./publish --no-build

    - name: Upload published app as artifact
      uses: actions/upload-artifact@v4
      with:
        name: AbbBackup-published
        path: ./publish
