name: Build AbbBackup Project (.NET Framework 4.8)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build AbbBackup.csproj
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build AbbBackup.csproj
      run: msbuild AbbBackup.csproj /p:Configuration=Release
