name: Build AbbBackup (.NET Framework 4.8)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on Windows with MSBuild
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Locate solution
      run: dir /s /b

    - name: Build solution
      run: msbuild AbbBackup.sln /p:Configuration=Release
